name: sync-fork
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh repo sync -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH_NAME: main
